---
nameinfo:
  agnesi.debian.org: Maria Teresa Agnesi (October 17, 1720 - January 19, 1795)
  albeniz.debian.org: Isaac Manuel Francisco Albéniz i Pascual (May 29, 1860 - May 18, 1909)
  ancina.debian.org: Giovanni Giovenale Ancina (19 October 1545 - August 30, 1604)
  arcadelt.debian.org: Jacques Arcadelt (also Jacob Arcadelt) (?1507 - October 14, 1568)
  argento.debian.org: Dominick Argento (b. October 27, 1927)
  bartok.debian.org: Béla Viktor János Bartók (March 25, 1881 - September 26, 1945)
  brahms.debian.org: Johannes Brahms (May 7, 1833 - April 3, 1897)
  carver.debian.org: Robert Carver (ca.1485 - ca.1570)
  chopin.debian.org: Frédéric Chopin (1 March 1810 - 17 October 1849)
  dijkstra.debian.org: Lowell Dijkstra (b.1952)
  draghi.debian.org: Antonio Draghi (1635 - 16 January  1700)
  duarte.debian.org: Leonora Duarte (28 July  1610 - 1678)
  gluck.debian.org: Christoph Willibald Ritter von Gluck (2 July 1714 - 15 November 1787)
  goedel.debian.org: Kurt Gödel (April 28, 1906 - January 14, 1978)
  goetz.debian.org: Hermann Gustav Goetz (December 7, 1840 - December 3, 1876)
  handel.debian.org: Georg Friedrich Händel (23 February 1685 - 14 April 1759)
  kassia.debian.org: Kassia (between 805 and 810 - bef. 867)
  klecker.debian.org: Dedicated to Joel 'Espy' Klecker (1979 - July 11, 2000)
  lafayette.debian.org: Eugenie Lafayette
  lebrun.debian.org: Francesca Lebrun (March 24, 1756 - May 14, 1791)
  mahler.debian.org: Gustav Mahler (7 July 1860 - 18 May 1911)
  mayr.debian.org: Johann(es) Simon Mayr (June 14, 1763 - December 2, 1845)
  merkel.debian.org: Gustav (Adolf) Merkel (November 12, 1827 - October 30, 1885)
  merulo.debian.org: Claudio Merulo (8 April 1533 - 4 May 1604)
  morales.debian.org: Cristóbal de Morales (c. 1500 - between September 4 and October 7, 1553)
  mundy.debian.org: William Mundy (c. 1529 - 1591)
  paer.debian.org: Ferdinando Paër (July 1, 1771 - May 3, 1839)
  penalosa.debian.org: Francisco de Peñalosa (c. 1470 - April 1, 1528)
  pergolesi.debian.org: Giovanni Battista Pergolesi (4 January 1710 - 16 or 17 March 1736)
  peri.debian.org: Jacopo Peri (20 August 1561 - 12 August 1633)
  pescetti.debian.org: Giovanni Battista Pescetti (ca. 1704  - 1766)
  piatti.debian.org: Carlo Alfredo Piatti (January 8, 1822 - July 18, 1901)
  powell.debian.org: Andrew Powell (b. 18 April 1949)
  praetorius.debian.org: Hieronymus Praetorius (10 August 1560 - 27 January 1629)
  puccini.debian.org: Giacomo Antonio Domenico Michele Secondo Maria Puccini (December 22, 1858 - November 29, 1924)
  raff.debian.org: Joseph Joachim Raff (May 27, 1822 - June 24 or June 25, 1882)
  ravel.debian.org: Joseph-Maurice Ravel (March 7, 1875 - December 28, 1937)
  ries.debian.org: Franz Ries (1846-1932)
  rietz.debian.org: August Wilhelm Julius Rietz (December 28, 1812 - September 12, 1877)
  rore.debian.org: Cipriano de Rore (occasionally Cypriano) (1515 or 1516 - between September 11 and September 20, 1565)
  saens.debian.org: Charles-Camille Saint-Saëns  (9 October 1835 - 16 December 1921)
  sarti.debian.org: Giuseppe Sarti (baptised December 1, 1729 - July 28, 1802)
  schein.debian.org: Johann Hermann Schein (January 20, 1586 - November 19, 1630)
  schroeder.debian.org: Hermann Schroeder (1904 - 1984)
  schumann.debian.org: Robert Alexander Schumann (8 June 1810 - 29 July 1856)
  smetana.debian.org: Bedřich Smetana (2 March 1824 - 12 May 1884)
  sperger.debian.org: Johannes Matthias Sperger (March 23, 1750 - May 13, 1812)
  spohr.debian.org: Louis Spohr (5 April 1784 - 22 October 1859)
  spontini.debian.org: Gaspare Luigi Pacifico Spontini (14 November 1774 - 24 January 1851)
  steffani.debian.org: Agostino Steffani (25 July 1653 - 12 February 1728)
  strauss.debian.org: Johann Baptist Strauß (October 25, 1825 - June 3, 1899)
  tartini.debian.org: Giuseppe Tartini (April 8, 1692 - February 26, 1770)
  unger.debian.org: Caroline Unger (October 28, 1803 - March 23, 1877)
  verdi.debian.org: Giuseppe Fortunino Francesco Verdi (October 9 or 10, 1813 - January 27, 1901)
  voltaire.debian.org: François-Marie Arouet (Voltaire) (21 November 1694 - 30 May 1778)
  wagner.debian.org: Wilhelm Richard Wagner (22 May 1813 - 13 February 1883)
  widor.debian.org: Charles-Marie Jean Albert Widor (February 21, 1844 - March 12, 1937)
  wieck.debian.org: Clara Josephine Wieck (September 13, 1819 - May 20, 1896)
  zelenka.debian.org: Jan Dismas Zelenka (16 October 1679 - 23 December 1745)
footer:
  bartok.debian.org: "Documentation: gluck:/org/admin.debian.org/doc/backup.debian.org"
  lebrun.debian.org: "- This host is using an iptables firewall.  See /etc/rc.boot/firewall{,6}"
  schroeder.debian.org: "- This host is using an iptables firewall.  See /etc/rc.boot/firewall{,6}"
  verdi.debian.org: "- This host is using an iptables firewall.  See /etc/ferm/ferm.conf"
  zelenka.debian.org: "Debian s390 porter system kindly provided by Zentrum fuer Informationsverarbeitung und Informationstechnik [zivit]"
need_smarthost:
  - ancina.debian.org
  - allegri.debian.org
  - piatti.debian.org
heavy_exim:
  - raff.debian.org
  - gluck.debian.org
  - merkel.debian.org
  - spohr.debian.org
  - draghi.debian.org
  - master.debian.org
  - ries.debian.org
  - rietz.debian.org
  - klecker.debian.org
  - powell.debian.org
apache2_defaultconfig:
  - carver.debian.org
  - draghi.debian.org
  - duarte.debian.org
  - piatti.debian.org
  - rore.debian.org
  - samosa.debian.org
  - tartini.debian.org
services:
  bugsmaster: rietz.debian.org
  qamaster: merkel.debian.org
  mailrelay: spohr.debian.org
  rtmaster: spohr.debian.org
  packagesmaster: powell.debian.org
  packagesqamaster: master.debian.org
mail_port:
  ancina.debian.org: 2025
  allegri.debian.org: 2025
  piatti.debian.org: 2025
  kassia.debian.org: 587
reservedaddrs:
  ball.debian.org: "0.0.0.0/8 : 127.0.0.0/8 : 10.0.0.0/8 : 169.254.0.0/16 : 172.16.0.0/12 : 192.0.0.0/17 : 192.168.0.0/16 : 224.0.0.0/4 : 240.0.0.0/5 : 248.0.0.0/5"
---

